### ISSUE TITLE
crash/panic doing `ls`

### ISSUE THREAD

**Issue by RichardBronosky** [genuinetools/reg#52]
Failure mode:

```
$ reg -r docker.int ls
Repositories for docker.int
REPO                       TAGS
lighttpd-docker            1.0.1, 1.0.0
event-apiweather-service   1.0.0, 1.1.0, 1.2.0, latest 1.5.0, 1.4.0, 1.3.0-SNAPSHOT, 1.1.0, 1.2.0, latest
panic: runtime error: slice bounds out of range [recovered]
	panic: tabwriter: panic during Flush [recovered]
	panic: tabwriter: panic during Write

goroutine 132 [running]:
text/tabwriter.handlePanic(0xc42023dee0, 0x1417580, 0x5)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:458 +0x117
panic(0x1388ec0, 0xc42047c8b0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
text/tabwriter.handlePanic(0xc42023ddd0, 0x14174ea, 0x5)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:458 +0x117
panic(0x13ac260, 0x1631760)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
text/tabwriter.(*Writer).writeLines(0xc4200fe100, 0x89, 0x3, 0x5, 0x89)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:297 +0x495
text/tabwriter.(*Writer).format(0xc4200fe100, 0x0, 0x3, 0x5, 0x5)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:385 +0x2e5
text/tabwriter.(*Writer).flush(0xc4200fe100, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:484 +0x189
text/tabwriter.(*Writer).Flush(0xc4200fe100, 0xc42024c4e0, 0x4)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:467 +0x2b
text/tabwriter.(*Writer).Write(0xc4200fe100, 0xc4202202d0, 0x2c, 0x30, 0x2c, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/text/tabwriter/tabwriter.go:518 +0x3df
main.main.func2.1(0xc4200fe100, 0xc4204aa380, 0xc4204aa370, 0xf)
	/Users/bbronosky/Go/src/github.com/jessfraz/reg/main.go:153 +0x311
created by main.main.func2
	/Users/bbronosky/Go/src/github.com/jessfraz/reg/main.go:146 +0x225
```

Since `docker.int` is a private repo you cannot reach, I can offer you:

```
$ while read; do echo "## $REPLY"; reg -r docker.int tags $REPLY; done < repos
## admin-ui
1.0.2
1.0.3
1.0.1
1.0.6
1.0.0
1.0.7
1.0.5
1.0.4
latest
## admin-ui-prod
1.0.16
1.0.13
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.14
1.0.8
## admin-ui-uat
1.0.16
1.0.13
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.14
1.0.8
## alpine
latest
## android-installer
1.0.1
1.0.0
## appliance-service
1.11.0
1.6.0
1.15.0
1.16.0
1.28.0
1.29.0
1.20.0
1.24.0
1.9.0
1.3.0
1.0.0
1.18.0
1.7.0
1.5.0
1.4.0
1.25.0
1.30.0
1.17.0
1.10.0
1.13.0
1.31.0
1.19.0
1.12.0
1.23.0
1.1.0
1.14.0
1.8.0
1.22.0
1.27.0
1.2.0
1.26.0
1.21.0
latest
## billing-meter-service
1.6.0
0.3
1.3.0
1.0.0
1.5.0
1.4.0
0.2
0.4
1.1.0
1.2.0
latest
## comm-jarvis-analytics
latest
## comm-jarvis-app
gunicorn
latest
henri
## comm-message-api
1.3.0
1.0.0
1.5.0
1.4.0
1.1.0
1.2.0
latest
## comm-preference-api
1.3.0
1.0.0
1.4.0
1.1.0
1.2.0
latest
## comm-processor
1.6.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.1.0
1.2.0
latest
## comm-validator
1.11.0
1.6.0
1.9.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.10.0
1.4.0-SNAPSHOT
1.1.0
1.8.0
1.2.0
latest
## config-service
1.6.0
1.3.0
1.0.0
1.7.0
1.5.0
1.0.0-SNAPSHOT
1.4.0
1.1.0
1.2.0
latest
## config-service-reader
1.0.0
1.0.0-SNAPSHOT
latest
## config-service-writer
1.0.0
1.0.0-SNAPSHOT
latest
## consumer-ui
3.154.0
3.139.0
3.153.0
3.152.0
3.144.0
3.146.0
3.135.0
3.143.0
3.145.0
3.149.0
3.142.0
3.141.0
3.138.0
3.136.0
3.140.0
3.148.0
3.147.0
3.137.0
3.151.0
latest
3.150.0
## customer-control-charts-data
2de7142
3d2a8c8
653b1c1
0871d6f
d7620e0
## datavault-service
0.1
1.0.0
1.1.0
latest
## dependencies-service
1.2.3
1.0.0
1.2.2
1.2.1
1.1.0
1.2.0
latest
## device-collector-service
1.0.2
1.0.29
1.0.18
1.0.21
1.0.22
1.0.23
1.0.3
1.0.27
1.0.36
1.0.16
1.0.1
1.0.25
1.3.0
1.0.6
1.0.0
1.5.0
1.0.7
1.4.0
1.0.13
1.0.5
1.0.19
1.0.30
1.0.4
1.0.32
1.0.26
1.0.31
1.0.35
1.0.33
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.1.0
1.0.17
1.0.28
1.0.14
1.2.0
latest
1.0.8
1.0.24
1.0.34
1.0.20
## device-grid-microservice
1.3.0
1.0.0
1.5.0
1.4.0
1.1.0
1.2.0
latest
## device-installer-ui
1.0.2
1.0.18
1.0.21
1.0.22
1.0.23
1.0.3
1.0.27
1.0.16
1.0.1
1.0.25
1.0.6
1.0.0
1.0.7
1.0.13
1.0.5
1.0.19
1.0.4
1.0.26
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.14
1.0.8
1.0.24
1.0.20
## device-installer-ui-prod
1.0.29
1.0.36
1.0.30
1.0.32
1.0.31
1.0.35
1.0.33
1.0.28
1.0.34
## device-installer-ui-uat
1.0.29
1.0.36
1.0.30
1.0.32
1.0.31
1.0.35
1.0.33
1.0.28
1.0.34
## device_grid
3.154.0
3.139.0
3.153.0
3.152.0
3.144.0
3.146.0
3.143.0
3.145.0
3.149.0
3.142.0
3.141.0
3.138.0
3.136.0
3.140.0
3.148.0
3.147.0
3.137.0
3.151.0
latest
3.150.0
## devicecloud-microservice
1.0.0
1.1.0
latest
## docker-java8
latest
## docker-jre8-alpine
1.0.0
## docker-jre8-alpine-alpn
1.0.2
1.0.3
1.0.1
1.0.0
## docker-scala-2.10.4
latest
## ema-ui-prod
1.0.2
1.0.29
1.0.18
1.0.21
1.0.22
1.0.3
1.0.27
1.0.16
1.0.1
1.0.25
1.0.6
1.0.0
1.0.7
1.0.13
1.0.5
1.0.19
1.0.4
1.0.26
1.0.11
1.0.23b
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.28
1.0.14
1.0.22b
1.0.8
1.0.24
1.0.20
## ema-ui-uat
1.0.2
1.0.29
1.0.18
1.0.21
1.0.22
1.0.3
1.0.27
1.0.16
1.0.1
1.0.25
1.0.6
1.0.0
1.0.7
1.0.13
1.0.5
1.0.19
1.0.4
1.0.26
1.0.11
1.0.23b
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.28
1.0.14
1.0.22b
1.0.8
1.0.24
1.0.20
## email-service
1.11.0
0.1
1.6.0
1.9.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.10.0
1.12.0
0.2
1.1.0
1.8.0
1.2.0
latest
## redacted-service
1.0.0
1.1.0
1.2.0
latest
## redacted-monitor-server
3.1.0
3.1.0-SNAPSHOT-a5b2637
## event-alert-service
1.0.0
1.1.0
1.2.0
latest
## event-api
1.6.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.3.0-SNAPSHOT
1.1.0
1.2.0
latest
## fluentd-alpine-elasticsearch
1.0.0
## health-check
1.3.0
1.0.0
1.1.0
1.2.0
latest
## heapster_riemann
canary
## home-status-processor
1.6.0
1.3.0
1.0.0
1.5.0
1.4.0
1.3.0-SNAPSHOT
1.4.0-debug
1.1.0
1.2.0
latest
## ies-vacant-home-runner
v1.2
## ies-vsftpd
1.0.0
## ies-redacted
latest
## iesartifactory
latest
## iesbackup
1.0.2
1.0.1
1.0.0
## iesdns
latest
## iesjenkins
1.0.3
test_b
1.0.6
test_c
1.0.7
1.0.13
1.0.5
1.0.4
test_a
1.0.11
1.0.9
1.0.10
1.0.12
1.0.14
latest
1.0.8
## iesnagios
1.0.1
1.0.0
## installer-service
1.11.0
1.6.0
1.15.0
1.16.0
1.20.0
1.9.0
1.3.0
1.0.0
1.18.0
1.7.0
1.5.0
1.4.0
1.17.0
1.10.0
1.13.0
1.19.0
1.12.0
1.1.0
1.14.0
1.8.0
1.2.0
latest
## internal-control-charts-data
653b1c1
0871d6f
## internal-control-charts-data-ipc
2de7142
d7620e0
## internal-control-charts-data-smud
3d2a8c8
d7620e0
## irom-core
3.5.0
3.6.0
3fb5de2
a5245e7
91e6579
4c6adfd
## irom-core-integration
3.5.0
3.6.0
b6a21df
eb2cf16
## irom-plugins
3.10.0-SNAPSHOT
3.5.2
latest
## irom-rt
3.154.0
3.139.0
3.153.0
3.152.0
3.144.0
3.146.0
3.143.0
3.145.0
3.149.0
3.142.0
3.141.0
3.138.0
3.136.0
3.140.0
3.148.0
3.147.0
3.137.0
3.151.0
latest
3.150.0
## irom-ws
3.5.0
3.6.0
3fb5de2
91e6579
## iromcoremonitor
latest
## java
1.0.0
## jenkins
1.0.10
## knife
11
## redacted
latest
## lighttpd-docker
1.0.1
1.0.0
## misc-jobs
latest
## mv-runner
3.25.0
3.25.1
2.0
## nagios3
20150812_backup
latest
## network-utilities-service
1.0.0
latest
## network-utils-service
1.0.2
14d7808
1.0.3
v1.0.1
1.1.1
1.3.0
1.0.6
1.0.0
1.4.0
1.0.5
0.1.0
1.0.6-SNAPSHOT
1.1.3
1.0.4
1.4.1
1.1.2
1.2.1
v0.0.1
1.1.0
1.2.0
latest
## nginx-admin-ui-prod
1.0.18
1.0.21
1.0.22
1.0.23
1.0.16
1.0.19
1.0.15
1.0.17
1.0.24
1.0.20
## nginx-admin-ui-uat
1.0.2
1.0.18
1.0.21
1.0.22
1.0.23
1.0.3
1.0.16
1.0.1
1.0.6
1.0.0
1.0.7
1.0.13
1.0.5
1.0.19
1.0.4
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.14
1.0.8
1.0.24
1.0.20
## nginx-ema-ui-prod
1.0.0
## nginx-ema-ui-uat
1.0.0
## nginx-installer-ui-prod
1.0.18
1.0.16
1.0.17
## nginx-installer-ui-uat
1.0.2
1.0.18
1.0.3
1.0.16
1.0.1
1.0.6
1.0.0
1.0.7
1.0.13
1.0.5
1.0.4
1.0.11
1.0.15
1.0.9
1.0.10
1.0.12
1.0.17
1.0.14
1.0.8
## nginx-jwt
1.0.0
## nginx-php
latest
## node-service
1.6.0
1.9.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.9.1
1.10.0
1.1.0
1.8.0
1.2.0
latest
## nw-utils
latest
## openadr
latest
## push-notification-service
0.1
0.3
0.5
0.2
0.4
latest
## pushnotification-service
0.16
0.17
0.10
0.8
0.21
0.12
0.14
0.22
0.15
0.11
0.13
0.20
0.6
0.7
0.18
0.19
0.9
latest
0.23
## resident-billing-meter-service
0.1
latest
## root
3.7.0-SNAPSHOT
## salesforce-service
1.1.0
latest
## sms-service
1.6.0
1.9.0
1.3.0
1.7.0
1.5.0
1.4.0
1.1.0
1.8.0
1.2.0
latest
## sysintegration
latest
## ubuntu14-oracle-jre7
1.0.0
## ubuntu14-oracle-jre7-yjp
1.0.0
## user-service
1.11.0
1.6.0
1.9.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.10.0
1.13.0
1.12.0
1.1.0
1.8.0
1.2.0
latest
## vacant-home-api
1.0.2
1.0.3
1.0.1
1.0.6
1.0.0
1.0.7
1.0.5
1.0.4
1.0.9
latest
1.0.8
## verification-service
1.6.0
1.9.0
1.3.0
1.0.0
1.7.0
1.5.0
1.4.0
1.1.0
1.8.0
1.2.0
latest
## weather-service
1.0.0
1.1.0
1.2.0
latest
```

**Comment by jessfraz** [comment]
can you still reproduce this on master?

**Comment by jessfraz** [comment]
closing but please let me know if you still see this on master, thanks!
