### ISSUE TITLE
reg-0.14.0 - reg ls -> fatal error: concurrent map writes 

### ISSUE THREAD

**Issue by mrueg** [genuinetools/reg#97]
I hit this regression with 0.14.0 on a private docker registry.
It works with 0.13.4

reg is compiled with golang-1.10.2
```
# reg ls private.docker.registry
fatal error: concurrent map writes

goroutine 330 [running]:
runtime.throw(0xa35573, 0x15)
        /usr/lib/go/src/runtime/panic.go:616 +0x81 fp=0xc420821ea0 sp=0xc420821e80 pc=0x42c291
runtime.mapassign_faststr(0x962a80, 0xc42041abd0, 0xc420230980, 0x16, 0x4)
        /usr/lib/go/src/runtime/hashmap_fast.go:703 +0x3e9 fp=0xc420821f10 sp=0xc420821ea0 pc=0x40db09
main.glob..func4.1(0xc42024d620, 0xc42041abd0, 0xc4203eeb80, 0xc420230980, 0x16)
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/list.go:53 +0x19e fp=0xc420821fb8 sp=0xc420821f10 pc=0x8c65ae
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420821fc0 sp=0xc420821fb8 pc=0x458921
created by main.glob..func4
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/list.go:45 +0x20c

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4203eeb8c)
        /usr/lib/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4203eeb80)
        /usr/lib/go/src/sync/waitgroup.go:129 +0x72
main.glob..func4(0xc4200ef340, 0xc42024d500, 0xc4200ef340)
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/list.go:58 +0x23b
github.com/genuinetools/reg/vendor/github.com/urfave/cli.HandleAction(0x93f800, 0xa57508, 0xc4200ef340, 0x0, 0xc42024d560)
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/genuinetools/reg/vendor/github.com/urfave/cli.Command.Run(0xa2a119, 0x4, 0x0, 0x0, 0xdbb320, 0x1, 0x1, 0xa35780, 0x15, 0x0, ...)
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/genuinetools/reg/vendor/github.com/urfave/cli.(*App).Run(0xc420310540, 0xc42001e090, 0x3, 0x3, 0x0, 0x0)
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
        /var/tmp/portage/app-emulation/reg-0.14.0/work/reg-0.14.0/src/github.com/genuinetools/reg/main.go:84 +0x86b

goroutine 5 [syscall]:
os/signal.signal_recv(0x434378)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 739 [select]:
net/http.setRequestCancel.func3(0x0, 0xc4205a8480, 0xc420346140, 0xc4203fe018, 0xc42009a300)
        /usr/lib/go/src/net/http/client.go:323 +0xfa
created by net/http.setRequestCancel
        /usr/lib/go/src/net/http/client.go:322 +0x2ac

goroutine 3291 [select]:
net/http.(*persistConn).writeLoop(0xc4200bec60)
        /usr/lib/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1238 +0x97f

goroutine 22 [select]:
net/http.setRequestCancel.func3(0x0, 0xc420336120, 0xc4202a2000, 0xc4203ee00c, 0xc420402120)
        /usr/lib/go/src/net/http/client.go:323 +0xfa
created by net/http.setRequestCancel
        /usr/lib/go/src/net/http/client.go:322 +0x2ac

goroutine 16 [select]:
net/http.setRequestCancel.func3(0x0, 0xc4205a8240, 0xc420346000, 0xc4203fe010, 0xc42009a0c0)
        /usr/lib/go/src/net/http/client.go:323 +0xfa
created by net/http.setRequestCancel
        /usr/lib/go/src/net/http/client.go:322 +0x2ac

goroutine 15 [chan receive]:
net/http.(*persistConn).addTLS(0xc420386fc0, 0xc4201bb400, 0xf, 0x0, 0xc4201bb410, 0x3)
        /usr/lib/go/src/net/http/transport.go:1074 +0x1c8
net/http.(*Transport).dialConn(0xdc9620, 0xaa0f80, 0xc420026118, 0x0, 0xc42043ec60, 0x5, 0xc4201bb400, 0x13, 0x67a5cc, 0x1, ...)
        /usr/lib/go/src/net/http/transport.go:1153 +0x14c3
net/http.(*Transport).getConn.func4(0xdc9620, 0xaa0f80, 0xc420026118, 0xc420200780, 0xc420028de0)
        /usr/lib/go/src/net/http/transport.go:957 +0x78
created by net/http.(*Transport).getConn
....
```

**Comment by jessfraz** [comment]
fixed and pushed a new version
